### PR TITLE
Update: pre-commit configuration with ruff and codespell

### PR DESCRIPTION
**Pull request by geminixiang**
### Description
This pull request updates the `pre-commit` configuration by adding two new tools, "ruff" and "codespell," and also updates the versions of existing tools to ensure the best code quality and consistency. 

#### Pre-commit Configuration Updates
- **pre-commit/pre-commit-hooks**: Updated to `v4.5.0`
  - Add the `check-toml` hook.
  - Updated the order of hooks for consistency.
- **psf/black**: Updated to `23.10.0`.
  - Removed the `--exclude` argument from the `black` hook.
- **astral-sh/ruff-pre-commit**: Added a new repository and tool `ruff`.
- **pycqa/isort**: No changes, remains at `5.12.0`.
- **codespell-project/codespell**: Added a new repository and tool `codespell`.

#### Local Hooks
- **mypy**: No changes, remains the same with specific configuration.

### Why
These updates are essential to enhance our code quality, maintainability, and overall development process. The new tools, "ruff" and "codespell," will help us improve code formatting and identify and fix spelling mistakes in the codebase. 

Happy birthday, Patty.

### Checklist
- [x] Updated pre-commit configuration.
- [x] Added new tools, "ruff" and "codespell."
- [x] Updated tool versions for consistency.
- [x] Ensured the `mypy` configuration remains unchanged.
- [x] Checked for any potential conflicts or issues with the new tools.
- [x] Confirmed that pytest does not report any errors.

### CODE REVIEW

**Review by lucemia — DISMISSED** [review]
Thanks

**Comment by geminixiang** [comment]
python 3.10 & 3.11 builds are not functioning correctly

**Comment by lucemia** [comment]
> python 3.10 & 3.11 builds are not functioning correctly

看起來好像是 Github Open Source Project 為了保護 Secret 不外露，對於其他人的 PR 不會自動跑 CI 的緣故
但是應該有個方式可以 trigger, 還沒時間查

**Comment by geminixiang** [comment]
有額外更新 trigger condition~

**Review by lucemia — APPROVED** [review]

**Pull request merged**
